// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT


// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as http$0 from "../../../../net/http/models.js";

export interface EnvResult {
    "appName": string;
    "basePath": string;
    "os": string;
    "arch": string;
    "x64Level": number;
}

export interface ExecOptions {
    "convert": boolean;
    "env": { [_: string]: string } | null;
}

export interface FlagResult {
    "flag": boolean;
    "data": string;
}

export interface FlagResultWithData {
    "flag": boolean;
    "msg": string;
    "data": any;
}

export interface HTTPResult {
    "flag": boolean;
    "header": http$0.Header;
    "body": string;
}

export interface MenuItem {
    /**
     * Menu Type: item / separator
     */
    "type": string;
    "text": string;
    "tooltip": string;
    "event": string;
    "children": MenuItem[] | null;
    "hidden": boolean;
    "checked": boolean;
}

export interface TrayContent {
    "icon": string;
    "title": string;
    "tooltip": string;
}
