// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT


export interface BiliMetadata {
    "SavedFilePath": string;
    "SelectedVideoStreamUrl": string;
    "SelectedVideoQuality": string;
    "SelectedVideoCodecs": string;
    "Cr": CidResponse;
    "Vir": VideoInfoResponse;
}

export interface CidResponse {
    "data": {"bvid": string, "cid": number, "pic": string, "title": string};
}

export interface VideoInfoResponse {
    "data": {"accept_description": string[] | null, "accept_quality": number[] | null, "support_formats": {"quality": number, "new_description": string, "codecs": string[] | null}[] | null, "dash": {"video": {"id": number, "base_url": string, "backupUrl": string[] | null, "bandwidth": number, "codecs": string, "width": number, "height": number}[] | null, "audio": {"base_url": string, "bandwidth": number}[] | null}};
}
