// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call} from "@wailsio/runtime";

/**
 * Name returns the name of the plugin.
 * You should use the go module format e.g. github.com/myuser/myplugin
 */
export function Name(): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1967292100) as any;
    return $resultPromise;
}
